services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

      
  backend:
    build:
      context: ./backend
    container_name: backend-py
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8000:8000
    depends_on:
      - postgres