services:
  postgres:
    image: postgres:13-alpine
    container_name: todo-db-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

      
  backend:
    build:
      context: ./backend
      args:
        BACKEND_VERSION: ${BACKEND_VERSION}
    image: todo-backend:latest
    container_name: todo-backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/tododb
      BACKEND_VERSION: ${BACKEND_VERSION}
    ports:
      - 8000:8000
    depends_on:
      - postgres
  

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_VERSION: ${REACT_APP_VERSION}
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    image: todo-frontend:latest
    container_name: todo-frontend
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - postgres
      - backend